command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: DATABRICKS_HOST
    value: "{{dbr-host}}"

  - name: HTTP_PATH
    value: "{{sql-warehouse}}"

  - name: ANTHROPIC_API_KEY
    value: "{{claude-api}}"
