command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: dbr-host
    valueFrom: "dbr-host"

  - name: sql-warehouse
    valueFrom: "sql-warehouse"

  - name: dbr-token
    valueFrom: "dbr-token"

  - name: claude-api
    valueFrom: "claude-api"
